### ISSUE TITLE
NumberFormatException 관련 문의 드립니다.

### ISSUE THREAD

**Issue by sungjini78** [neolord0/hwpxlib#10]
안녕하세요
제공해 주신 라이브러리 사용 중 일부 파일에서 NumberFormatException이 발생하여 문의 드립니다.
오류가 발생하는 파일 첨부합니다.
감사합니다.

[presentation오류.zip](https://github.com/neolord0/hwpxlib/files/14967547/presentation.zip)

**Comment by neolord0** [comment]
안녕하세요
올려주신 hwpx파일로 테스트 해 봤습니다.
Presentation 부분의 showtime 항목의 값이 Integer 변수로 되어 있었으나. 
올려주신 hwpx파일에는 Integer 변수로 담을 수 없는 값을 가지고 있습니다.
Presentation 부분에서 showtime 항목의 타입을 Integer => Long 으로 변경하였습니다.

**Comment by sungjini78** [comment]
수고해 주셔서 감사합니다.
