### ISSUE TITLE
HWPXReader클래스의 fromFile 메서드 호출 오류.

### ISSUE THREAD

**Issue by do1231** [neolord0/hwpxlib#11]
안녕하세요.
덕분에 한글 파일을 읽기가 수월하게 해결되었는데 HWP는 문제가 없으나 HWPX에서 오류가 발생을 하여 문의드립니다.
fromFile 메서드를 호출하였을 때 NullPointerException이 발생을 합니다.

java.lang.NullPointerException
	at kr.dogfoot.hwpxlib.reader.HWPXReader.packagedFiles(HWPXReader.java:111)
	at kr.dogfoot.hwpxlib.reader.HWPXReader.read(HWPXReader.java:77)
	at kr.dogfoot.hwpxlib.reader.HWPXReader.fromFile(HWPXReader.java:30)
	at kr.dogfoot.hwpxlib.reader.HWPXReader.fromFilepath(HWPXReader.java:20)

포함된 리소스로 디버깅해 보니 packagedFiles() 메서드 코드 중 hwpxFile.contentHPFFile().manifest() 반환값이 null로 확인이 되는데
포함된 리소스의 111라인은 빈줄로 보여집니다.(이클립스 사용)

참고로 JDK는 1.8이고, gradle설정은 다음과 같습니다.
	implementation group: 'kr.dogfoot', name: 'hwplib', version: '1.1.6'
	**implementation group: 'kr.dogfoot', name: 'hwpxlib', version: '1.0.3'**

감사합니다.

**Comment by neolord0** [comment]
안녕하세요.
에러나는 파일을 올려주세요.
파일을 작성한 한글 프로그램에 버전별로 파일이 약간씩 다릅니다.

**Comment by do1231** [comment]
답변 감사합니다.

한글파일은 neolord0님이 올려 놓으신 다음 링크의 HWPX파일로 테스트 하였습니다.
https://github.com/neolord0/hwpxlib/blob/main/testFile/reader_writer/SimpleContainer.hwpx

한글파일과 테스트한 java소스파일 압축하여 업로드해 드립니다.
[docu_test.zip](https://github.com/neolord0/hwpxlib/files/15384415/docu_test.zip)

오류나는 부분은 111줄이 아닌 108줄입니다. (디버깅하려고 추가했던 소스의 class파일이 남아 있었네요.)

java.lang.NullPointerException
	at kr.dogfoot.hwpxlib.reader.HWPXReader.packagedFiles(HWPXReader.java:108)
	at kr.dogfoot.hwpxlib.reader.HWPXReader.read(HWPXReader.java:77)
	at kr.dogfoot.hwpxlib.reader.HWPXReader.fromFile(HWPXReader.java:30)
	at test.doc.hwp.HWPReadTest2.parseHWPX(HWPReadTest2.java:111)
	at test.doc.hwp.HWPReadTest2.init(HWPReadTest2.java:57)
	at test.doc.hwp.HWPReadTest2.<init>(HWPReadTest2.java:44)
	at test.doc.hwp.HWPReaderTest.main(HWPReaderTest.java:36)

감사합니다.

**Comment by neolord0** [comment]
저의 개발 환경에서는 잘 되는데, 이런 경우는 디버그 하기 어렵네요.

음.. 혹시 JDK를 Oracle 이외의 것을 사용하시나요 ?? 

hwpxFile.contentHPFFile().manifest() 이 null이라는 것은 

kr.dogfoot.hwpxlib.reader.content_hpf.PackageReader 클래스에 
![image](https://github.com/neolord0/hwpxlib/assets/24711108/e2058abd-1c34-4431-9dde-667818e4c20b)
이 부분이 실행되지 않았다는 건데...

System.out.println() 함수등을 사용하여 이 부분이 실행 되었는지 확인 해주셨으면 합니다.
앞에서 애기했듯이.. do1231님 환경에서만 에러가 나서.. 테스트해 주셨으면 합니다.
 
감사합니다.

**Comment by Ggyumalang** [comment]
안녕하세요! 덕분에 hwplib를 잘 사용하고 있습니다. 너무 감사드립니다.
저 또한 hwpxlib 1.0.3 을 사용 중에 이슈 남겨주신 분과 똑같은 에러가 발생하여 글 남깁니다.
제 JDK는 1.8이며 테스트 파일은 올려주신 샘플 파일로 하였습니다.
그런데 hwpxlib 소스를 깃에서 클론하여 테스트로 실행시키면 정상 작동 합니다. 혹시 maven repository에 올라간 소스와 지금의hwpxlib 소스가 상이한 점이 있어서 그런 것인지..모르겠습니다.

감사합니다

**Comment by neolord0** [comment]
아.. 그럴수도 있겠군요. 테스트 해보겠습니다.
Ggyumalang 님  적절한 조언 감사합니다.

**Comment by neolord0** [comment]
안녕하세요..
시간이 돼서.. 제 개발환경(mac, java7) 과 다른 
윈도우즈 환경에서 hwpxlib 1.0.3 버전을 maven 저장소에서 받아서 테스트 해봤습니다.

아래와 같은 여러 개의 1.8 버전, 1.7버전을 테스트 해봤는데.. 문제가 없네요..
![image](https://github.com/neolord0/hwpxlib/assets/24711108/10e8a745-07ef-4019-a05b-9c4dd8e50d90)

do1231님이 사용하신 OS나 jdk을 알려주시면 테스트 해보겠습니다.
