### ISSUE TITLE
hwpxlib에서 테이블 데이터 추출 과정에서 궁금한 점이 있어 문의 드립니다.

### ISSUE THREAD

**Issue by JangHyuckYun** [neolord0/hwpxlib#12]
안녕하세요. 만들어주신 hwpxlib를 활용해서 테이블 데이터를 추출하고, 텍스트를 추출하려는 과정에서, 어떻게해야 텍스트를 출력할 수 있는지 모르겠더라고요..

hwplib의 경우에는 Paragraph 클래스안에서 각 HwpChar의 문자열 코드를 통해 가져왔지만, hwpxlib에서는 그렇게 할 수 없는것 같더군요.. 다른 방법이 있을까요??

**Comment by neolord0** [comment]
안녕하세요

테이블의 데이터, 텍스트 등을 추출하려면
kr.dogfoot.hwpxlib.tool.textextractor 패키지 아래 클래스 들을 사용하거나, 이 코드를 참고하시면 될 거 같습니다.

확인 해 보세요.

**Comment by JangHyuckYun** [comment]
관련 코드를 찾아서 테스트를 진행했고 잘 되는것을 확인 했습니다! 감사합니다!
