### ISSUE TITLE
HPWX 파일 실행 오류. ( application/hwp+zip )

### ISSUE THREAD

**Issue by JangHyuckYun** [neolord0/hwpxlib#13]
안녕하세요! hwpx 라이브러리를 사용하면서 테이블 데이터를 추출하려는 도중에, 일부 파일의 경우 파일 자체를 불러오지 못하는 현상이 발생을 했더라구요..

## 환경 정보
- OS: Windows 11
- Java: 1.8.0_321 ( 1.8 )
- Spring Boot 2.3.5 / Maven 환경
- IDE: Intellij
- hwpxlib 4.0.0 버전 사용중.

## 에러
외부에서 받은 hwpx 파일을 new File 객체로 생성하여 넘겨주었을 때,
```text
java.io.IOException: not hwpx file
```
이런 에러가 나타나더라구요. 디버깅을 통해 확인해보니, 
해당 파일의 확장자는 "application/hwp+zip" 으로 되어있고,
HWPXReader.java에서 71번째 줄의 manifestXML() 메서드 실행 부근에서 에러가 발견이 되었는데,
zipFile.getEntry를 하는 과정에서 zipEntry의 값이 null이라 발생한 문제더라구요. openZipFile메서드에서 제대로 값을 불러오지 못한것으로 보이는데, 일부는 되고 일부는 안되니 정확한 원인을 찾기 어려워 질문 남깁니다..

![스크린샷 2024-06-26 104325](https://github.com/neolord0/hwpxlib/assets/43720558/9383ff5f-fb3e-4c90-beb1-6761a552d368)

**Comment by neolord0** [comment]
안녕하세요..
제 생각에는 "application/hwp+zip" 는 zip으로 압축된 hwp 파일이 아닐까 추측됩니다.
java zip 라이브러러로 내용을 압축을 풀어서 hwplib로 읽는 방법을 테스트 해보세요.

이렇게 해서 안되면 그 파일을 이 게시물에 첨부해 주세요.

**Comment by JangHyuckYun** [comment]
넵 감사합니다! 지금 테스트 해보겠습니다!

**Comment by JangHyuckYun** [comment]
일단 zip 라이브러리로 테스트를 해보고는 있는데 잘 안되는 것 같아서.. 올려두겠습니다..!
[fail_hwpx_file.zip](https://github.com/user-attachments/files/15982491/fail_hwpx_file.zip)

**Comment by neolord0** [comment]
올려주신 hwpx 파일 내부에 "manifest.xml" 파일이 없어서 오류가 난 거 같습니다.
이 파일은 OpenOffice 파일 표준 포맷에서 사용되는 건데, hwpx 는 사용하지 않는 거 같습니다.
읽지 않아도 문제가 없네요..
 
이 파일이  한글이 아닌 다른 프로그램에 의해 생성된 거 같습니다.

**Comment by neolord0** [comment]
코드 수정하였습니다.
다시 받아서 테스트 해보세요.
maven 레포지토리에는 조망간 올리겠습니다.

**Comment by JangHyuckYun** [comment]
오호 그렇군요..  내부적으로는 같은 파일이라도 다른 포맷으로 사용되기도 하는가 보군요.. 감사합니다..! 지금 테스트 해보겠습니다!

**Comment by JangHyuckYun** [comment]
대단하시네요.. 테스트 해봤는데, 덕분에 잘 동작합니다..! 감사합니다!!
