### ISSUE TITLE
테이블의 Cell 하위에 있는 테이블 추출 방법이 궁금합니다.

### ISSUE THREAD

**Issue by JangHyuckYun** [neolord0/hwpxlib#14]
안녕하세요!

아래 사진처럼 테이블 Cell 안에 추가로 테이블 정보가 있는 경우, Tc 클래스나 CellSpan 클래스에서 테이블이 추가로 있음을 확인 후, 가져오는 방법이 있는지 궁금합니다..!

![image](https://github.com/neolord0/hwpxlib/assets/43720558/b62f68e9-b0da-4a5c-828b-2887e24637c3)

**Comment by neolord0** [comment]
안녕하세요.
github 홈페이지에서 밝혔듯이 버그관련 사항은 무료 입니다만,  
사용법에 대한 질문은 기술지원 라이센스를 구입해야 합니다.
감사합니다.
