### ISSUE TITLE
안녕하세요, 좋은 라이브러리 공개해주셔서 감사합니다.
HWPX 파일 포맷을 분석해보고 있는 학생입니다.
한글 공식 문서에서는 HWPX 파일에서 사용되는 요소 스키마 등을 공개하지 않았는지 OWPML 국가표준 자료 밖에 찾을 수 없었습니다.
그럼에도 라이브러리 내부에서는 실제 HWPX파일에서 사용되는 요소들에 특성들이 모두 있더군요. 특히 열거형으로 정의해야하는 타입들은 각 값들에 일관성도 없어서 많은 어려움을 겪고 있습니다. 예를들어 어떤 열거형의 값은 모두 영문 대문자로 되어있지만 어떤건 첫 문자만 대문자로 정의 되어 있다던지..
혹시 standard.go.kr에 공개되어있는 OWPML 문서외에 참고하신 자료가 있다면 알려주실 수 있으실까요?

### ISSUE THREAD

**Issue by MaJaeGeon** [neolord0/hwpxlib#15]

**Comment by neolord0** [comment]
안녕하세요.

OWPML 이외의 참고한 자료는 없습니다.
OWPML에서 부족한 부분이나 맞지 않는 부분은 실험을 통해 검증하여 추가/수정했습니다.

님이 지적하신 열거형 등의 코드 일관성에 대한 문제는 
OWPML 문서의 표현을 그대로 사용했기 때문입니다.
밥벌이 일을 하면서 소소하게 하는 일이라 수정하는데 드는 
시간/노력을 줄이기 위해  그런 방법을 취했습니다.

OWPML 문서도 여러 명의 한컴 개발자들이 만든 것이기 때문에 부분적으로 
서로 다를 수 있습니다.

정 불편하시다면 소스가 공개되어 있으니, 직접 수정하면 됩니다.
