### ISSUE TITLE
headerXml 에 대한 paraPr의 문단속성정보가 이상합니다.  

### ISSUE THREAD

**Issue by wavor** [neolord0/hwpxlib#16]
hwpx파일을 읽었을때, 문단에 대한 들여쓰기와 Line간 간격을 읽으려고 합니다.
그런데, 실제 hwpx파일의 header.xml에는 다음과 같이 paraPr에 대한 줄간격과 문단들여쓰기 정보가 있는데,
<hh:paraPr id="12" tabPrIDRef="0" condense="0" fontLineHeight="0" snapToGrid="1" suppressLineNumbers="0" checked="0"><hh:align horizontal="JUSTIFY" vertical="BASELINE"/><hh:heading type="BULLET" idRef="1" level="0"/><hh:breakSetting breakLatinWord="KEEP_WORD" breakNonLatinWord="KEEP_WORD" widowOrphan="0" keepWithNext="0" keepLines="0" pageBreakBefore="0" lineWrap="BREAK"/><hh:autoSpacing eAsianEng="0" eAsianNum="0"/><hp:switch><hp:case hp:required-namespace="http://www.hancom.co.kr/hwpml/2016/HwpUnitChar"><hh:margin><hc:intent value="0" unit="HWPUNIT"/><hc:left value="2500" unit="HWPUNIT"/><hc:right value="0" unit="HWPUNIT"/><hc:prev value="0" unit="HWPUNIT"/><hc:next value="0" unit="HWPUNIT"/></hh:margin><hh:lineSpacing type="PERCENT" value="160" unit="HWPUNIT"/></hp:case><hp:default><hh:margin><hc:intent value="0" unit="HWPUNIT"/><hc:left value="5000" unit="HWPUNIT"/><hc:right value="0" unit="HWPUNIT"/><hc:prev value="0" unit="HWPUNIT"/><hc:next value="0" unit="HWPUNIT"/></hh:margin><hh:lineSpacing type="PERCENT" value="160" unit="HWPUNIT"/></hp:default></hp:switch><hh:border borderFillIDRef="3" offsetLeft="0" offsetRight="0" offsetTop="0" offsetBottom="0" connect="0" ignoreMargin="0"/></hh:paraPr>

=> headerXMLFile.refList().paraProperties().items() 로 읽어 보면,
  ParaPr 클래스의 속성 내용중 lineSpacing과 margin에 대한 속성값이 null 로 나옵니다.

해당 정보가 정상적으로 나오게 하려면 어떻게 해야 하나요.
[테스트파일.zip](https://github.com/user-attachments/files/16904532/default.zip)

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    안녕하세요.<hp:switch/> 에 들어 있습니다. 한글 버전 별로 다른값이 들어갈 수 있는 부분은 그렇게 처리하는 거 같습니다.--------- 원본 메일 ---------

  
    보낸사람: wavor ***@***.***>
    받는사람: neolord0/hwpxlib ***@***.***>
      참조: Subscribed ***@***.***>
    날짜: 24.09.06 16:43 GMT +0900
    
    제목: [neolord0/hwpxlib] headerXml 에 대한 paraPr의 문단속성정보가 이상합니다.   (Issue #16)
    
    
  
  
    
hwpx파일을 읽었을때, 문단에 대한 들여쓰기와 Line간 간격을 읽으려고 합니다.
그런데, 실제 hwpx파일의 header.xml에는 다음과 같이 paraPr에 대한 줄간격과 문단들여쓰기 정보가 있는데,
<hh:paraPr id="12" tabPrIDRef="0" condense="0" fontLineHeight="0" snapToGrid="1" suppressLineNumbers="0" checked="0"><hh:align horizontal="JUSTIFY" vertical="BASELINE"/><hh:heading type="BULLET" idRef="1" level="0"/><hh:breakSetting breakLatinWord="KEEP_WORD" breakNonLatinWord="KEEP_WORD" widowOrphan="0" keepWithNext="0" keepLines="0" pageBreakBefore="0" lineWrap="BREAK"/><hh:autoSpacing eAsianEng="0" eAsianNum="0"/>hp:switch<hp:case hp:required-namespace="http://www.hancom.co.kr/hwpml/2016/HwpUnitChar">hh:margin<hc:intent value="0" unit="HWPUNIT"/><hc:left value="2500" unit="HWPUNIT"/><hc:right value="0" unit="HWPUNIT"/><hc:prev value="0" unit="HWPUNIT"/><hc:next value="0" unit="HWPUNIT"/></hh:margin><hh:lineSpacing type="PERCENT" value="160" unit="HWPUNIT"/></hp:case>hp:defaulthh:margin<hc:intent value="0" unit="HWPUNIT"/><hc:left value="5000" unit="HWPUNIT"/><hc:right value="0" unit="HWPUNIT"/><hc:prev value="0" unit="HWPUNIT"/><hc:next value="0" unit="HWPUNIT"/></hh:margin><hh:lineSpacing type="PERCENT" value="160" unit="HWPUNIT"/></hp:default></hp:switch><hh:border borderFillIDRef="3" offsetLeft="0" offsetRight="0" offsetTop="0" offsetBottom="0" connect="0" ignoreMargin="0"/></hh:paraPr>
=> headerXMLFile.refList().paraProperties().items() 로 읽어 보면,
ParaPr 클래스의 속성 내용중 lineSpacing과 margin에 대한 속성값이 null 로 나옵니다.
해당 정보가 정상적으로 나오게 하려면 어떻게 해야 하나요.
테스트파일.zip

**Comment by wavor** [comment]
감사합니다.
버전에 따라 저장방법이 다른가 보내요
