### ISSUE TITLE
문서내에 하이퍼링크가 등록된 경우, url주소에 & 또는 &amp; 가 있을 경우, StringParam의 vale값이 이상함

### ISSUE THREAD

**Issue by wavor** [neolord0/hwpxlib#17]
문서내에 특정 문자열에 대해 하이퍼링크를 다음과 같이 추가한 경우
http://naver.com/article?id=1111&amp;param=2222

section0.xml 상에서 <hp:fieldBegin><hp:parameters><hp:stringParam>http://naver.com/article?id=1111&amp;param=2222</hp:stringParam></hp:parameters>
이렇게 이상없이 들어있는데

hwpxlib 상에서 해당 stringParam에 대한 value는 &amp; 다음의 문자만 나옵니다.

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    안녕하세요."http://naver.com/article?id=1111&amp;param=2222"  이  URL은 다음과 같이 저장되더군요.				<hp:fieldBegin id="1632929776" type="HYPERLINK" name="" editable="0" dirty="1" zorder="-1" fieldid="627600491" metaTag="">					<hp:parameters cnt="6" name="">						<hp:integerParam name="Prop">0</hp:integerParam>						<hp:stringParam name="Command">http\://naver.com/article\?id=1111&amp;amp\;param=2222;1;0;0;</hp:stringParam>						<hp:stringParam name="Path">http://naver.com/article?id=1111&amp;amp;param=2222</hp:stringParam>						<hp:stringParam name="Category">HWPHYPERLINK_TYPE_URL</hp:stringParam>						<hp:stringParam name="TargetType">HWPHYPERLINK_TARGET_BOOKMARK</hp:stringParam>						<hp:stringParam name="DocOpenType">HWPHYPERLINK_JUMP_CURRENTTAB</hp:stringParam>					</hp:parameters>				</hp:fieldBegin>이렇게 입력해 주면 되지 않을까 생각됩니다.파일이  hwpx 파일은  zip파일이기 때문에.. 풀면 xml이 보입니다.xml 파일을 보시면 파악할 수 있으리라 생각됩니다,회사 정책상 오류 수정 이외의 기술지원은 유료로 대응해야 합니다.--------- 원본 메일 ---------

  
    보낸사람: wavor ***@***.***>
    받는사람: neolord0/hwpxlib ***@***.***>
      참조: Subscribed ***@***.***>
    날짜: 24.09.08 19:34 GMT +0900
    
    제목: [neolord0/hwpxlib] 문서내에 하이퍼링크가 등록된 경우, url주소에 & 또는 & 가 있을 경우, StringParam의 vale값이 이상함 (Issue #17)
    
    
  
  
    
문서내에 특정 문자열에 대해 하이퍼링크를 다음과 같이 추가한 경우
http://naver.com/article?id=1111&amp;param=2222
section0.xml 상에서 hp:fieldBeginhp:parametershp:stringParamhttp://naver.com/article?id=1111&amp;param=2222</hp:stringParam></hp:parameters>
이렇게 이상없이 들어있는데
hwpxlib 상에서 해당 stringParam에 대한 value는 & 다음의 문자만 나옵니다.

**Comment by wavor** [comment]
답변주신 xml형식은 저도 알겠습니다.
그런데, 여기에서 XML상에서의 Path정보를 읽어들인
 fieldBegin.parameters().params()에서 param.name() = 'Path' 일때
  (StringParam) param의 value 값이 앞의 부분이 잘리고
   url 맨뒤에 있는 &amp; 뒤에 값으로 나옵니다. 
   
 정상적으로 xml의 stringParam에 있는 Path 값으로 나오게 수정해주실 수 있나요?
 아마도 StringParamReader 클래스에서 다음과 수정하면 어떨까요...
@Override
    public void text(String text) {
    	if((this.stringParam.name().equals("Command") || this.stringParam.name().equals("Path")) && this.stringParam.value() != null) {
    		stringParam.value(this.stringParam.value() + text);
    	} else
    		stringParam.value(text);
    }
 
[테스트문서.zip](https://github.com/user-attachments/files/16925712/default.zip)

**Comment by neolord0** [comment]
안녕하세요.
조금 늦었지만,  해결했습니다.
SAX 파서를 사용하여 XML를 파싱하는데,  
이 파서가 XML text에 특수문자가 있을 경우, 이벤트를 나눠서 발생시켜 주네요..
님이 하신 방식이랑 비슷하게 수정했습니다.
