### ISSUE TITLE
파일 읽는 중 오류 발생

### ISSUE THREAD

**Issue by seoulcity** [neolord0/hwpxlib#18]
안녕하세요. hwpx 파서 중에 가장 업데이트가 활발하게 이루어지고 있는 것 같아 사용을 시도해보았습니다만, 읽는 과정에서 에러가 발생했습니다.

`java.lang.NullPointerException: Cannot invoke "kr.dogfoot.hwpxlib.reader.common.ElementReader.started(boolean)" because "this.currentElementReader" is null`

읽기 시도한 파일도 함께 첨부합니다. (hwpx 업로드 제한으로 zip으로 변경하여 업로드하였습니다)
[mot.zip](https://github.com/user-attachments/files/17499664/mot.zip)

감사합니다.

**Comment by neolord0** [comment]
안녕하세요.. 바빠서 시간내기 힘드네요.
올려주신 파일을 보니까. 필드랑 셀(표) 개체에 metaTag라는 값이 추가 되었네요..
그래서, 오류가 발생했고.. 수정하여 올려놨습니다.
소스 받아서 테스트 해보세요.
