### ISSUE TITLE
currentElementReader null 에러?

### ISSUE THREAD

**Issue by sdk0213** [neolord0/hwpxlib#3]
```kotlin
val file = FileManager.createFileFromInputStream(context = applicationContext, inputStream = inputStream, fileName = name)
                                    val hwpxFile: HWPXFile = HWPXReader.fromFile(file)


                                    val sb = java.lang.StringBuilder()

                                    val countOfXML = hwpxFile.sectionXMLFileList().count()
                                    for(i in 0 until countOfXML){
                                        val countOfPara = hwpxFile.sectionXMLFileList()[i].countOfPara()
                                        for(j in 0 until countOfPara){
                                            val countOfRun = hwpxFile.sectionXMLFileList()[i].getPara(j).countOfRun()
                                            for(t in 0 until countOfRun){
                                                val countOfRunItem = hwpxFile.sectionXMLFileList()[i].getPara(j).getRun(t).countOfRunItem()
                                                for(w in 0 until countOfRunItem){
                                                    if(hwpxFile.sectionXMLFileList()[i].getPara(j).getRun(t).getRunItem(w) is T){
                                                        val text: T? = hwpxFile.sectionXMLFileList()[i].getPara(j).getRun(t).getRunItem(w) as T
                                                        text?.let {
                                                            if(text.isOnlyText){
                                                                sb.append(text.onlyText()).append("\n")
                                                            }
                                                        }
                                                        text?.items()?.let {
                                                            text.items().forEach { tTiem ->
                                                                if(tTiem._objectType() == ObjectType.NormalText){
                                                                    sb.append((tTiem as NormalText).text())
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }

                                        }
                                    }
```

위와 같은 코드로 문서 내 텍스트를 파싱중인데 **hwpx 가 두개 이상일때 에러가 발생합니다.**

java.lang.NullPointerException: Attempt to invoke virtual method 'void kr.dogfoot.hwpxlib.reader.common.ElementReader.started(boolean)' on a null object reference
                                                                                                    	at kr.dogfoot.hwpxlib.reader.common.XMLFileReader.endElement(XMLFileReader.java:93)
                                                                                                    	at kr.dogfoot.hwpxlib.reader.ContentFilesReader.endElement(ContentFilesReader.java:85)
                                                                                                    	at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:167)

```java
    @Override
    public void endElement(String uri, String localName, String name) {
        if(currentElementReader != null) {
            currentElementReader.started(false);
            currentElementReader.endElement();
            elementReaderManager.release(currentElementReader);

            if (currentElementReader.previousReader() == null) {
                currentElementReader = null;
            } else {
                currentElementReader = currentElementReader.previousReader().switchableObjectReader() ? currentElementReader.previousReader().previousReader() : currentElementReader.previousReader();
            }
        }
    }
```

위 부분에 currentElementReader != null 조건을 추가하고 에러가 발생하지는 않는데 근본적으로 다른문제 일것같아서 이슈항목에 올렸습니다.

코드에 대한 미숙한 사용으로 발생한 에러라면 이슈 종료하셔도 될것같습니다.

그리고 아래부분 답변 해주시면 감사하겠습니다.

1. 그리고 Text 추출 관련하여 위와같이 복잡하게 Section xml 을 읽어와야 하는것이 정석인지 테스트 샘플코드를 많이 작성해주셨는데 확신이 가지 않는데 이런식으로 하는것이 맞나요?
2. hwplib 처럼 inputstream 으로 가져오는 방식은 아직 개발이 안된것인지도 궁금합니다.  
3. Maven 에 아직 등록이 안된것인가요? pom.xml 은 있는데 가져오지 못해서 다운로드받아서 사용중입니다.

**Comment by neolord0** [comment]
안녕하세요..
일단, 에러에 대해서는 파일을 읽어오는 부분에서 오류가 나는 것 같습니다.
특정 hwpx 파일이 한컴이 제공한 포맷 문서와 다른게 아닐까 생각됩니다.  
버전이 바뀔때마다 조금씩 변경되는 경우가 있습니다.  에러나는 hwpx파일을 올려주시면 테스트 해보겠습니다.

1.  Text 추출은 대략적으로는 님이 하는 방식이 맞습니다. 이 부분은 시간이 날 때 작업을 해서 라이브러리에 포함하거나 별도로 배포할 생각입니다. 
2. hwpx 는 zip 파일이라... inputstream시 stream으로 읽어오는 zip 파일 내부에 파일들을 특정 순서대로 읽어야 하는데.. 이 부분이 좀 어려운 거 같습니다. 좀 더 고민해 보겠습니다. 
3. 네..아직 등록전 입니다. 전체적으로 시간이 부족한 관계로 이 일은 우선순위에서 한참 밀리고 있습니다. 

이상입니다.

**Comment by sdk0213** [comment]
![image](https://user-images.githubusercontent.com/51182964/233514444-d4674d85-fa6f-42cb-a6ce-0983fe54655a.png)

발생한 문제에 대해서 금일 다시 확인해보니 파일의 개수가 아닌

차트 도표가 들어가있을경우 해당 문제가 발생합니다.

hwp 파일 upload 가 불가하니 google drvie 링크와 해당 문서 정보 남깁니다.

![image](https://user-images.githubusercontent.com/51182964/233514757-95ae3043-79ed-4a25-926b-0db451fa289a.png)

hwp 테스트파일 : https://drive.google.com/file/d/1-0aeQi8OSMbS1bt9GWL4FGq4Tu2RltbU/view?usp=sharing


제가 테스트한 환경은 Android OS 이며 이는 Andorid OS 문제와 관련된것일수도 있으니 참고부탁드립니다.

**Comment by neolord0** [comment]
수정하여 패치 했습니다.
테스트 해보세요..

제가 HWP 2014버전을 가지고 있어서 2014버전에서 생성된 파일 만을  테스트해서  
상위 버전에서 생성된 파일에서 달리진 부분이 오류가 난 거 같습니다.
