### ISSUE TITLE
hwpx 파일 읽는 중 오류가 발생합니다

### ISSUE THREAD

**Issue by JiniApp** [neolord0/hwpxlib#5]
안녕하세요 
파일 읽는 중 오류가 발생하여 문의 드립니다.

java.lang.NullPointerException: Cannot invoke "kr.dogfoot.hwpxlib.reader.common.ElementReader.started(boolean)" because "this.currentElementReader" is null

이와 같은 오류가 발생하였고 테스트한 파일 첨부했습니다.

[test.zip](https://github.com/neolord0/hwpxlib/files/12280301/test.zip)

**Comment by neolord0** [comment]
안녕하세요
수정했습니다.
다시 받아서 테스트 해보세요.

**Comment by JiniApp** [comment]
감사합니다.
