### ISSUE TITLE
오타가 있는 거 같아서 글 남깁니다.

### ISSUE THREAD

**Issue by JiniApp** [neolord0/hwpxlib#7]
안녕하세요 좋은 라이브러리 제공해 주셔서 항상 감사드리며 
MM_0_7 부분에 오타가 있는 거 같아서 글 남깁니다.

public enum LineWidth implements EnumGetStr, EnumGetIndex {
    MM_0_1("0.1 mm", (byte) 0),
    MM_0_12("0.12 mm", (byte) 1),
    MM_0_15("0.15 mm", (byte) 2),
    MM_0_2("0.2 mm", (byte) 3),
    MM_0_25("0.25 mm", (byte) 4),
    MM_0_3("0.3 mm", (byte) 5),
    MM_0_4("0.4 mm", (byte) 6),
    MM_0_5("0.5 mm", (byte) 7),
    MM_0_6("0.6 mm", (byte) 8),
    MM_0_7("0.7 mm", (byte)  7),  <-- 9
    MM_1_0("1.0 mm", (byte) 10),
    MM_1_5("1.5 mm", (byte) 11),
    MM_2_0("2.0 mm", (byte) 12),
    MM_3_0("3.0 mm", (byte) 13),
    MM_4_0("4.0 mm", (byte) 14),
    MM_5_0("5.0 mm", (byte) 15);

**Comment by neolord0** [comment]
안녕하세요..
그렇군요. 오타가 있었네요.  지적 감사합니다. 수정해서 올렸습니다.
앞으로도 이상한 부분이 있으면 지적해주세요.
