### ISSUE TITLE
의뢰 문의 메일을 드렸습니다. 

### ISSUE THREAD

**Issue by getroot** [neolord0/hwpxlib#8]
neolord@hanmail.net로 메일 드렸는데 체크 부탁 드립니다.

**Comment by neolord0** [comment]
요즘 바빠서... 이제야 확인 해봤습니다.
메일이 안 왔습니다. 다시 보내주세요..

**Comment by getroot** [comment]
메일 다시 포워딩 했습니다. 혹시 스팸함도 한번 체크 부탁 드립니다.

**Comment by neolord0** [comment]
안녕하세요. 라움소프트 박성균입니다.

먼저 hwplib와 hwplibx를 유용하게 활용하신다니 개발자로서 보람을 느낍니다.
hwplib와 hwplibx는 오픈소스로서 사회에 기여하는 입장에서 진행하고 있는 프로젝트입니다.
따라서 앞으로도 사용자의 의견을 반영하여 업그레이드를 해 나갈 예정입니다.

하지만 요청하신 사안처럼 우선순위를 두고 약속에 기반하여 진행하는 건에 대해서는
회사에 소속되어 있는 사람으로서 개인적인 진행에 부담을 가지고 있는 게 사실입니다.

따라서 이런 경우는 회사를 통해서 진행하는 게 맞다고 생각합니다.

제가 소속되어 있는 회사는 라움소프트란 회사로서 한글관련 제품 또한 취급하고 있습니다.

간단히  소개해 드리면
         한글로폼 - 한글과컴퓨터와 협력하여 만든 제품.
                                웹한글기안기(한글워드 웹버전)에 데이터를 넣을 수 있는 기능
          한글로젠 - hwplib, hwplibx 와 hwpgen (한글에 데이터를 넣을 수 있는 기능)
                                 묶음 제품. (웹디자이너 포함)

결론적으로
     적절한 비용과 범위를 산정하여 회사의 인건비로 처리해야 할 것 같습니다.

상세한 내용은 답신 부탁드립니다.

감사합니다.
