### ISSUE TITLE
NullPointerException 오류 문의드립니다.

### ISSUE THREAD

**Issue by JiniApp** [neolord0/hwpxlib#9]
안녕하세요  라이브러리 제공에 항상 감사드리며
사용 중 NullPointerException 오류가 발생하여 문의 드립니다.
감사합니다.

java.lang.NullPointerException: Cannot invoke "hwpxlib.reader.common.ElementReader.started(boolean)" because "this.currentElementReader" is null

[2022.zip](https://github.com/neolord0/hwpxlib/files/14478133/2022.zip)

**Comment by neolord0** [comment]
안녕하세요..

올려주신 hwpx을 분석해 보니.. 색인 기능을 사용해서 그에 해당하는 정보들이 저장되어 있었습니다.
색인 기능에 해당하는 정보들을 파싱할 수 없어서.. 일단은 무시하게 처리했습니다. 
받아서 테스트 해보세요.

**Comment by JiniApp** [comment]
감사합니다. 잘 사용하겠습니다.
